import nodemailer from "nodemailer";
import { logger } from "./logger";

export async function sendContactNotification(
  name: string,
  senderEmail: string,
  messageText: string
): Promise<boolean> {
  const emailUser = process.env.EMAIL_USER;
  const emailPass = process.env.EMAIL_PASS;
  const smtpHost = process.env.SMTP_HOST || "smtp.gmail.com";
  const smtpPort = Number(process.env.SMTP_PORT || "465");
  const notificationEmail = process.env.NOTIFICATION_EMAIL || "harish23alr@gmail.com";

  if (!emailUser || !emailPass) {
    logger.warn(
      "SMTP credentials (EMAIL_USER/EMAIL_PASS) are not set. Skipping outbound email notification."
    );
    return false;
  }

  try {
    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465, // Use SSL/TLS for port 465
      auth: {
        user: emailUser,
        pass: emailPass,
      },
    });

    const subject = `🚀 Portfolio Contact Alert: Message from ${name}`;
    const textContent = `You have received a new contact submission from your portfolio website!

Sender Name: ${name}
Sender Email: ${senderEmail}
Timestamp: ${new Date().toLocaleString()}

Message:
---------------------------------------------
${messageText}
---------------------------------------------

Action Required: Please follow up with the user at ${senderEmail}.
`;

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #f8fafc;">
        <h2 style="color: #0ea5e9; font-family: monospace; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;">
          TRANSMISSION_ALERT
        </h2>
        <p style="font-size: 15px; color: #334155; line-height: 1.5;">
          You have received a new contact submission from your portfolio website!
        </p>
        <div style="background-color: #ffffff; padding: 15px; border-radius: 6px; border: 1px solid #cbd5e1; margin-top: 20px;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #64748b; width: 30%;">SENDER_NAME:</td>
              <td style="padding: 6px 0; color: #0f172a;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #64748b;">SENDER_EMAIL:</td>
              <td style="padding: 6px 0; color: #0ea5e9;"><a href="mailto:${senderEmail}" style="color: #0ea5e9; text-decoration: none;">${senderEmail}</a></td>
            </tr>
            <tr>
              <td style="padding: 6px 0; font-weight: bold; color: #64748b;">TIMESTAMP:</td>
              <td style="padding: 6px 0; color: #0f172a;">${new Date().toLocaleString()}</td>
            </tr>
          </table>
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 15px 0;" />
          <div style="font-weight: bold; color: #64748b; font-size: 12px; margin-bottom: 8px;">PAYLOAD_DATA:</div>
          <div style="white-space: pre-wrap; font-family: monospace; font-size: 13px; color: #0f172a; background-color: #f1f5f9; padding: 12px; border-radius: 4px; border: 1px solid #e2e8f0;">${messageText}</div>
        </div>
        <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-top: 25px;">
          This email was auto-generated by your portfolio api-server.
        </p>
      </div>
    `;

    const info = await transporter.sendMail({
      from: `"${name} (via Portfolio)" <${emailUser}>`,
      to: notificationEmail,
      subject: subject,
      text: textContent,
      html: htmlContent,
      replyTo: senderEmail,
    });

    logger.info({ messageId: info.messageId, to: notificationEmail }, "Email notification sent successfully");
    return true;
  } catch (error) {
    logger.error({ err: error }, "Failed to send email notification");
    return false;
  }
}
